language: python
python: '2.7'

env:
  global:
    - exit_code=0
    - number_per_job=2
    - message=()
    - ANSIBLE_CONFIG=/home/travis/.ansible/ansible.cfg
    - ANSIBLE_VERSION=2.9.15
  matrix:
    - id=1

before_install:
  - sudo apt-get update -qq
  - mkdir ~/.azure
  - touch ~/.azure/credentials
  - printf "[default]\nsubscription_id=$subscriptionId\nclient_id=$clientId\nsecret=$secret\ntenant=$tenant\n" > ~/.azure/credentials
  - cat ~/.azure/credentials
  - run_test(){
      file=$1;
      filename=${file##tests/integration/};
      test_name=${file##tests/integration/targets/};
      test_name=${test_name%%/tasks/main.yml};
      m=1;

      echo Run test $test_name from $filename;
      resource_group="asb-roletest-${test_name##azure_rm_}$(date +%s)";
      resource_prefix=$(date +%s);
      resource_group_secondary="asb-roletest-${test_name##azure_rm_}$(date +%s)2nd";
      travis_wait 80 ansible-playbook $file -v --extra-vars "{\"azure_subscription_id\":$AZURE_SUBSCRIPTION_ID,\"azure_tenant\":$AZURE_TENANT,\"azure_client_id\":$AZURE_CLIENT_ID,\"resource_group\":$resource_group}";

      if [ $? -ne 0 ]; then
        echo test $file failed;
        message+=($file);
        export exit_code=1;
      fi;

      if [ "$delete_resource_group" == true ]; then
         travis_wait 50 ansible-playbook ./__helpers/__delete_test_resource_group.yml --extra-vars "{\"azure_subscription_id\":$AZURE_SUBSCRIPTION_ID,\"azure_tenant\":$AZURE_TENANT,\"azure_client_id\":$AZURE_CLIENT_ID,\"resource_group_name\":$resource_group}";
      fi;
    }


  - scan_test() {
      end=$((id * number_per_job));
      start=$((end - number_per_job));
      branch=$TRAVIS_BRANCH;
      echo branch is $branch;
      run_test playbook.yml;	

    }

install:

install:
  - pip install ansible==2.9.15
  - sudo apt-get install -y git
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo usermod -aG docker ${USER}
  - sudo apt-get install -y default-jdk
  - sudo apt-get install -y maven sshpass
  - pip install ansible[azure]
  - ansible-galaxy install Azure.azure_preview_modules
  - pip install -I -r ~/.ansible/roles/Azure.azure_preview_modules/files/requirements-azure.txt
  - pip install azure_mgmt_privatedns 
  - pip install azure_cli_privatedns
  - pip install packaging
  - pip freeze
  - git clone https://github.com/Magopancione/docker-swarm.git 
  - ansible --version
  

script:
  - scan_test
  - exit $exit_code

notifications:
  email:
    - sonoilmagopancione@gmail.com


