   - name: Install lvm2
     yum:
       name: lvm2
       state: latest
     become: yes

   - name: extend volume
     lvol:
       vg: rootvg
       lv: varlv
       size: +100%FREE
     become: yes


   - name: resizing filesystem
     command: resize2fs /dev/mapper/rootvg-varlv
     become: yes
